### ISSUE TITLE
"Internal error" with amavis after upgrade from 1.9 to 1.10.0 / 1.10.1 with amavis 1.2.0

### ISSUE THREAD

**Issue by WhereIsPedro** [modoboa/modoboa-amavis#101]
After upgrade from 1.9.0  I have problem wih amavis Quarantine web GUI
Even if I have upgraded to current version and pasted "from modoboa_amavis import settings ....." 
On WebGUI Quarantine i have "Internal error" with meu, search and no information about queue / quarantine. Juest blank page below.
Anyway it doesn't matter if Im trying to get Quarantine module on webGUI by admin or user. Both we get the same error.
What else I can debug to help you ?
Thank you.

**System:**
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.3 LTS"

- Modoboa | 1.10.1 | 
- Amavis frontend | 1.2.0 |  
- IMAP migration using OfflineIMAP | 1.2.0 | 
- PDF credentials | 1.3.0 | 
- Postfix autoreply | 1.4.0 |  
- Radicale management | 1.2.0 | 
- Sieve filters | 1.4.0 |  
- Statistics | 1.4.0 |   
- Webmail | 1.4.0 |   

**Upgrade manual:**
http://modoboa.readthedocs.io/en/latest/upgrade.html

**DEBUG:**

```
domain.tld [pid: 4718|app: 1|req: 2/15] 172.16.1.1 () {64 vars in 1297 bytes} [Fri Feb 16 17:30:12 2018] GET /quarantine/ => generated 9572 bytes in 129 msecs (HTTP/1.0 200) 5 headers in 163 bytes (1 switches on core 0)

domain.tld  [pid: 4719|app: 1|req: 14/16] 172.16.1.1 () {64 vars in 1375 bytes} [Fri Feb 16 17:30:13 2018] GET /quarantine/listing/?sort_order=-date&reset_page=true&_=1518798610743 => generated 18416 bytes in 1903 msecs (HTTP/1.0 500) 5 headers in 169 bytes (1 switches on core 0)
```

**Status of " python manage.py check --deploy":**

```
?: (modoboa-amavis.W001) AMAVIS_DEFAULT_DATABASE_ENCODING does not match the character encoding used by the Amavis database.
        HINT: Check your database character encoding and set/update AMAVIS_DEFAULT_DATABASE_ENCODING.
?: (security.W004) You have not set a value for the SECURE_HSTS_SECONDS setting. If your entire site is served only over SSL, you may want to consider setting a value and enabling HTTP Strict Transport Security. Be sure to read the documentation first; enabling HSTS carelessly can cause serious, irreversible problems.
?: (security.W006) Your SECURE_CONTENT_TYPE_NOSNIFF setting is not set to True, so your pages will not be served with an 'x-content-type-options: nosniff' header. You should consider enabling this header to prevent the browser from identifying content types incorrectly.
?: (security.W007) Your SECURE_BROWSER_XSS_FILTER setting is not set to True, so your pages will not be served with an 'x-xss-protection: 1; mode=block' header. You should consider enabling this header to activate the browser's XSS filtering and help prevent XSS attacks.
?: (security.W008) Your SECURE_SSL_REDIRECT setting is not set to True. Unless your site should be available over both SSL and non-SSL connections, you may want to either set this setting True or configure a load balancer or reverse-proxy server to redirect all connections to HTTPS.
?: (security.W012) SESSION_COOKIE_SECURE is not set to True. Using a secure-only session cookie makes it more difficult for network traffic sniffers to hijack user sessions.
?: (security.W016) You have 'django.middleware.csrf.CsrfViewMiddleware' in your MIDDLEWARE, but you have not set CSRF_COOKIE_SECURE to True. Using a secure-only CSRF cookie makes it more difficult for network traffic sniffers to steal the CSRF token.
?: (security.W018) You should not have DEBUG set to True in deployment.
?: (security.W019) You have 'django.middleware.clickjacking.XFrameOptionsMiddleware' in your MIDDLEWARE, but X_FRAME_OPTIONS is not set to 'DENY'. The default is 'SAMEORIGIN', but unless there is a good reason for your site to serve other parts of itself in a frame, you should change it to 'DENY'.
```

**My changes:** 
`AMAVIS_DEFAULT_DATABASE_ENCODING = 'utf8' `
database in mysql: utf8_unicode_ci

**At the end of the settings.py there is:**
```
from modoboa_amavis import settings as modoboa_amavis_settings
modoboa_amavis_settings.apply(globals())
```

**Comment by tonioo** [comment]
Have you tried using the 1.2.2 version of the quarantine plugin?

**Comment by WhereIsPedro** [comment]
Hi Tonioo,
Didn't noticed that 1.2.2 exists :)
I think it's solved. 

One more question - is't normal for this 1.2.2 that TAB named "Disbplay bar" with buttons for faster filtering "S,V,B" that now is on the right side ? The same in IE & Chrome

PS. Also one more question: is there any way to change date format from M/D/Y for eg to: D/M/Y ?

**IMAGE:**
Like this: ![tab](http://i65.tinypic.com/2eg75z4.png[/IMG] )

**Comment by tonioo** [comment]
Yes, the right bar is normal and to change the date format, just use a different language.

**Comment by WhereIsPedro** [comment]
Thank you.
Status: SOLVED
