### ISSUE TITLE
How to disable bad header check?

### ISSUE THREAD

**Issue by akong77** [modoboa/modoboa-amavis#112]
Hello,
I will got some mail to quarantine and always show bad header.I see mail log.It's show

> Info: truncated 1 header line(s) longer than 998 characters.

It's my user send mail the same domain account.I know can release it.But I want know could disabled bad header check?

**Comment by tonioo** [comment]
@akong77 You can tweak bad header checks by editing amavis configuration. This page should be useful: https://www.prosinger.net/amavis-new-bad-header-checks-tweaking/.
