### ISSUE TITLE
Self-service emails not sent

### ISSUE THREAD

**Issue by dugite-code** [modoboa/modoboa-amavis#116]
I've enabled self service mode in the web interface however nothing is ever sent. The docs mention setting up a template however the link provided to the amavis docs only talk about spam and virus templates so I am not clear on how you set that up or even IF I have to set that up and that is part of the install process.

Installed using the installer script

Ubuntu 18.04.1 LTS

Modoboa | 1.12.2 | 
-- | -- | 
Amavis frontend | 1.2.3 |
DMARC tools | 1.1.0 | 
Statistics | 1.4.1 |
Webmail | 1.5.0

**Comment by tonioo** [comment]
@dugite-code Amavis sends notifications to local VIRUS/SPAM recipients. To enable this feature, try to add the following settings to amavis configuration:
```perl
$warnvirusrecip = 1;
$warn_offsite = 1;
```

**Comment by dugite-code** [comment]
Ah I see, because my modoboa install is `mail.example.tld` amavis sees `example.tld` as non-local. That makes sense.

I've modified the local domains acl  `@local_domains_acl = ( ".$mydomain", "example.tld" );` instead of adding the `$warn_offsite = 1;`

I'll see if this fixes my issue.

**Comment by dugite-code** [comment]
Just to follow up. The issue is amavis will not send spam quarantine notifications, it will only send virus quarantine notifications. From my reading there is no way to make it send spam quarantine notifications because "you're just replacing junk with junk"

I'm looking to see if it's possible to write a script that inspects the DB and send's a daily report to recipients
