### ISSUE TITLE
BAD HEADER SECTION Duplicate header field: "Cc"

### ISSUE THREAD

**Issue by tonyguadagno** [modoboa/modoboa-amavis#118]
hi, i am running modoboa 1.13.1 installed on centos7 using the auto installer.

I am seeing a lot of emails in quarantine because of this:
`BAD HEADER SECTION Duplicate header field: "Cc"`
The headers do seem to have duplicate cc: ...but why?  I am pretty sure the email was not generated initially with 2 cc fields.  is this a byproduct of amavis or something else?  how do i stop it?

thanks in advance?

**Comment by tonioo** [comment]
@tonyguadagno I don't know why your emails have 2 CC fields but you can tell amavis to not quarantine Bad header messages, just update the configuration like this:
```perl
$bad_header_quarantine_method = undef;
```
