### ISSUE TITLE
CSRF error: Cannot release or delete quarantine

### ISSUE THREAD

**Issue by stormleoxia** [modoboa/modoboa-amavis#120]
Hi,

I'm running modoboa 1.14.0 and modoboa-amavis 1.2.3 under a Python 2.7.12 virtual environment

I am unable to release or delete any quarantine mail.

It seems the CRSF token is wrong or not the one expected.

In the server:

```
WARNING 2019-12-03 15:31:34,267 csrf 10386 140337987282816 Forbidden (CSRF token missing or incorrect.): /quarantine/process/
```

In the browser:

```
jquery.min.js:5 POST https://mywebsite.com/quarantine/process/ 403 (Forbidden)
    send @ jquery.min.js:5
    ajax @ jquery.min.js:5
    _send_selection @ quarantine.js:262
    release_selection @ quarantine.js:277
    i @ jquery.min.js:3
    dispatch @ jquery.min.js:3
    v.handle @ jquery.min.js:3
    
VM1893:2 Uncaught SyntaxError: Unexpected token < in JSON at position 1
        at JSON.parse (<anonymous>)
        at Function.parseJSON (jquery.min.js:3)
        at Object.<anonymous> (quarantine.js:271)
        at c (jquery.min.js:3)
        at Object.fireWith [as rejectWith] (jquery.min.js:3)
        at k (jquery.min.js:5)
        at XMLHttpRequest.r (jquery.min.js:5)
    parseJSON @ jquery.min.js:3
    (anonymous) @ quarantine.js:271
    c @ jquery.min.js:3
    fireWith @ jquery.min.js:3
    k @ jquery.min.js:5
    r @ jquery.min.js:5
    XMLHttpRequest.send (async)
    send @ jquery.min.js:5
    ajax @ jquery.min.js:5
    _send_selection @ quarantine.js:262
    release_selection @ quarantine.js:277
    i @ jquery.min.js:3
    dispatch @ jquery.min.js:3
    v.handle @ jquery.min.js:3 
```

In the cookies, I have a cookie named `csrftoken`.

In `settings.py`:

```
X_FRAME_OPTIONS = "SAMEORIGIN"
CSRF_COOKIE_SECURE = True
CSRF_COOKIE_HTTPONLY = True
SESSION_COOKIE_SECURE = True
SESSION_EXPIRE_AT_BROWSER_CLOSE = False # Default value

```

**Comment by plvsouza** [comment]
Also I can not release or delete but does not show any errors. Using the same version modoboa 1.14.0 and modoboa-amavis 1.2.3

My settings.py

# Security settings

X_FRAME_OPTIONS = "SAMEORIGIN"
CSRF_COOKIE_SECURE = True
SESSION_COOKIE_SECURE = True

**Comment by soakes** [comment]
Hello,

I also have the same issue as OP.

My config file is default (unedited) and a fresh build/install the other week

```
X_FRAME_OPTIONS = "SAMEORIGIN"
CSRF_COOKIE_SECURE = True
SESSION_COOKIE_SECURE = True
```

![image](https://user-images.githubusercontent.com/813389/72218115-365cae00-352f-11ea-8a67-b69c86f937d9.png)

Whats interesting is, I can mark mails as spam/ham but I can't release, everything else works.

Any ideas on FIX anyone to be able to release mail which has been classified incorrectly?

Kind Regards,

Simon

**Comment by stormleoxia** [comment]
From what I understood, I think the post in the quarantine.js do not send the cookie as header request because the csrf.js cannot read it.

The current implementation in modoboar seems to assume that CSRF_USE_SESSIONS and CSRF_COOKIE_HTTPONLY are False: [Django](https://docs.djangoproject.com/en/3.0/ref/csrf/)

As the cookie is set as HTTPONLY, [browser doesn't permit to read it from javascript]
(https://stackoverflow.com/questions/8064318/how-to-read-a-http-only-cookie-using-javascript)

**Comment by stormleoxia** [comment]
so quickest fix for me was to set `CSRF_COOKIE_HTTPONLY`  to False in the `settings.py` 

    service uwsgi restart

- sign 
- out sign in

et voila ;)

**Comment by tonioo** [comment]
I guess a @csrf_exempt on the view would be a better solution here...

**Comment by xeeshan-Mustafa** [comment]
I am unable to release email but i can delete emails
