### ISSUE TITLE
Cannnot release mails form quarantine as super admin

### ISSUE THREAD

**Issue by felixlberg** [modoboa/modoboa-amavis#143]
I cannot release quarantine as super admin on Ubuntu 20.04.3

installed with: `sudo python3 ./run.py --stop-after-configfile-check`

Installed patch mentioned [here](https://github.com/modoboa/modoboa-amavis/issues/122):

```
Installing collected packages: modoboa-amavis
  Attempting uninstall: modoboa-amavis
    Found existing installation: modoboa-amavis 1.3.1
    Uninstalling modoboa-amavis-1.3.1:
      Successfully uninstalled modoboa-amavis-1.3.1
  Running setup.py develop for modoboa-amavis
Successfully installed modoboa-amavis-1.3.2.dev7
```

But it still not worked

```
XHRPOSThttps://mail.xxxx/quarantine/process/
[HTTP/1.1 500 Internal Server Error 102ms]
SyntaxError: JSON.parse: unexpected character at line 1 column 2 of the JSON data
"Connection to amavis failed: [Errno 13] Permission denied"
```

I tested `chmod 777 /var/lib/amavis/amavisd.sock` but without luck the problem persists.

kind regards

**Comment by felixlberg** [comment]
#122

**Comment by tonioo** [comment]
@felixlberg Have you checked what is the connection mechanism used in the settings you can find on the admin panel?

**Comment by felixlberg** [comment]
As i've written the connection method is `unix` otherwise it would make any sense to use a socket i guess.

After the default installation the option `PDP server socket` was pointing at another directory i had changed this to `/var/lib/amavis/amavisd.sock` otherwise amavis generally did not work and i had other errors in the logs. 

Changing the socket path to the actual amavis socket fixed that problem however it didn't fix the problem with the release of emails, maybe there is another hard coded amavis socket path for the release function, which isn't using the `PDP server socket` setting ?

Sry for my late reply i hope i can describe the problem more precisely with this.

kind regards

**Comment by felixlberg** [comment]
@tonioo Hey do you have some update regarding this issue?

**Comment by tonioo** [comment]
@felixlberg Have you checked amavis configuration for release setup? Is it listening on a unix socket or a UDP one?

**Comment by felixlberg** [comment]
@tonioo yes that seems to be the same path:
`sudo nano /usr/sbin/amavisd-release`
```
BEGIN {
### USER CONFIGURABLE:

  $log_level = 1;
# $socketname = '127.0.0.1:9998';
# $socketname = '[::1]:9998';
  $socketname = '/var/lib/amavis/amavisd.sock';

### END OF USER CONFIGURABLE
}

```

**Comment by felixlberg** [comment]
I don't think so cause its debian which has apparmour:
`sudo aa-status`
```
apparmor module is loaded.
13 profiles are loaded.
13 profiles are in enforce mode.
   /usr/bin/freshclam
   /usr/bin/man
   /usr/lib/NetworkManager/nm-dhcp-client.action
   /usr/lib/NetworkManager/nm-dhcp-helper
   /usr/lib/connman/scripts/dhclient-script
   /usr/sbin/clamd
   /usr/sbin/tcpdump
   /{,usr/}sbin/dhclient
   lsb_release
   man_filter
   man_groff
   nvidia_modprobe
   nvidia_modprobe//kmod
0 profiles are in complain mode.
2 processes have profiles defined.
2 processes are in enforce mode.
   /usr/bin/freshclam (831) 
   /usr/sbin/clamd (404) 
0 processes are in complain mode.
0 processes are unconfined but have a profile defined.
```

**Comment by tonioo** [comment]
@felixlberg And what happens if you switch to an INET connection?

**Comment by felixlberg** [comment]
@tonioo I've upgraded now to modoboa to v2.0 and modoboa_amavis to 1.4.0 and changed to inet connection.
Nothing worked though and I just see and popup window which says "undefined".

I could debug this by mysql If I just had some more info about how to rise the loglevel end where the amavis logs are stored. 
I simply just see any entries related with amavis eather in mail.log or in any other logs.

Where are the amavis logs and how can I log with debug level?

**Comment by tonioo** [comment]
That's indeed strange. I guess it's the kind of question you should ask on amavis mailing list because it looks like an internal security check or something similar...
