### ISSUE TITLE
Permission denied after fresh install

### ISSUE THREAD

**Issue by rhaamo** [modoboa/modoboa-amavis#23]
I've done a fresh install using installer and getting error with amavis:
```
Dec 15 09:34:42 derpy amavis[16380]: (16380-01) (!)run_av (ClamAV-clamd) FAILED - unexpected , output="/var/lib/amavis/tmp/amavis-20151215T153441-16380-aCsrzH3H/parts: lstat() failed: Permission denied. ERROR\n"
Dec 15 09:34:42 derpy amavis[16380]: (16380-01) (!)ClamAV-clamd av-scanner FAILED: CODE(0x4a5f280) unexpected , output="/var/lib/amavis/tmp/amavis-20151215T153441-16380-aCsrzH3H/parts: lstat() failed: Permission denied. ERROR\n" at (eval 100) line 905.
Dec 15 09:34:42 derpy amavis[16380]: (16380-01) (!)WARN: all primary virus scanners failed, considering backups
```

What can i do to correct that ?

**Comment by csmk** [comment]
Well, I think you need to configure amavis and clamAV correctly before start the integration with modoboa.

As the error says, you need to double-check the permittions in /var/lib/amavis :point_right: https://www.ijs.si/software/amavisd/INSTALL.txt

**Comment by rhaamo** [comment]
Well, all have been installed by modoboa installer.
Right are ok too and amavis is running under amavis user:
```
root@derpy:/etc/dovecot# ls -la /var/lib/amavis/tmp/
total 12
drwxr-x--- 3 amavis amavis 4096 Dec 15 16:19 .
drwxr-x--- 8 amavis amavis 4096 Dec 15 15:34 ..
drwxr-x--- 3 amavis amavis 4096 Dec 15 16:11 amavis-20151215T161131-19212-SaEJewIg
```

I think it's caused by clamav running under another user that amavis.

**Comment by csmk** [comment]
I see... You need to add the user "clamav" in the "amavis" group (and maybe vice versa too):

```
usermod -a -G amavis clamav
usermod -a -G clamav amavis
```

**Comment by tonioo** [comment]
The installer should already add clamav to the amavis group: https://github.com/modoboa/modoboa-installer/blob/master/modoboa_installer/scripts/clamav.py#L20

**Comment by Sn4kY** [comment]
Hi.
I have exactly the same problem. Fresh install on debootstraped Debian Jessie, problem still continues :
Jan  5 11:46:03 mail amavis[879]: (00879-06) (!)run_av (ClamAV-clamd) FAILED - unexpected , output="/var/lib/amavis/tmp/amavis-20160105T110044-00879-Z5j0MaPM/parts: lstat() failed: Permission denied. ERROR\n"
Jan  5 11:46:03 mail amavis[879]: (00879-06) (!)ClamAV-clamd av-scanner FAILED: CODE(0x356c458) unexpected , output="/var/lib/amavis/tmp/amavis-20160105T110044-00879-Z5j0MaPM/parts: lstat() failed: Permission denied. ERROR\n" at (eval 100) line 905.

clamav is, obviously, in the amavis group, and directory can be listed with sudo command : 

# sudo -u clamav ls -al /var/lib/amavis/tmp/amavis-20160105T110044-00879-Z5j0MaPM/parts
total 8
drwxr-x--- 2 amavis amavis 4096 Jan  5 11:46 .
drwxr-x--- 3 amavis amavis 4096 Jan  5 11:00 ..


The solution (given there : http://askubuntu.com/questions/604446/how-to-fix-amvavis-reporting-permission-denied-for-clamav/662672#662672) is to change the variable "AllowSupplementaryGroups" from "false" to "true".

**Comment by tonioo** [comment]
Thanks for the solution. I'll fix it into the installer.

**Comment by tonioo** [comment]
@Sn4kY Hey, what was the distribution you used please ?

**Comment by Sn4kY** [comment]
Debootstraped Debian Jessie (8.2)

**Comment by tonioo** [comment]
Ok, so I guess the default value on Debian is set to false. I've checked on a fresh Ubuntu and the value is already set to true.
