### ISSUE TITLE
cant see all mails in quarantine

### ISSUE THREAD

**Issue by blendi-93** [modoboa/modoboa-amavis#27]
Modoboa 	1.4.5 	1.4.5 	The core part of Modoboa
Amavis frontend 	1.0.6 	1.0.6 	Simple amavis management frontend

currently i have 10 mails in quarantine.
/user/#preferences/ set display count to a low number (5) so u shuld see multiple pages.

expected:
2 pages a 5 mail

but i only get 1 page without page navigation

**Comment by tonioo** [comment]
Since Modoboa paginates lists using the "infinite scroll" way, your content must reach the bottom before an another page is loaded. I suggest you set the setting to a high value (20 for example) so the bottom can be reached.

**Comment by blendi-93** [comment]
lol, ok thanks i'll try it.
