### ISSUE TITLE
CRON job error

### ISSUE THREAD

**Issue by spinza** [modoboa/modoboa-amavis#30]
Getting this cron error every minute (generated by cron email).

```
System check identified some issues:

WARNINGS:
modoboa_amavis.Msgrcpt.mail: (fields.W342) Setting unique=True on a ForeignKey has the same effect as using a OneToOneField.
        HINT: ForeignKey(unique=True) is usually better served by a OneToOneField.
modoboa_amavis.Quarantine.mail: (fields.W342) Setting unique=True on a ForeignKey has the same effect as using a OneToOneField.
        HINT: ForeignKey(unique=True) is usually better served by a OneToOneField.
```

**Comment by spinza** [comment]
Running latest version of everything.

**Comment by hydrandt** [comment]
I was getting identical warnings from the manage.py generate_rights cronjob, and from the rest of them later too. Reported it in modoboa-radicale issues:

https://github.com/modoboa/modoboa-radicale/issues/5

tonioo: "The second one is just a warning (unfortunately, I can't get rid of it) and you can ignore it by redirecting stdout to /dev/null."

Actually just redirecting stdout was not enough, these messages are in stderr.

**Comment by spinza** [comment]
Lol it's just ironic.  Was waiting for this version to stop a daily cron error, which is resolved (see https://github.com/modoboa/modoboa-amavis/issues/24).  

Now I get one every minute :D

**Comment by tonioo** [comment]
Can you try to add the following to your settings.py file please:
```python
SILENCED_SYSTEM_CHECKS = ["fields.W342", ]
```

**Comment by hydrandt** [comment]
Yes, that silences that warning successfully. Thank you!

Remove all your /dev/null redirections with:

<pre>sed -i "s/&> \/dev\/null/\ /g" /etc/cron.d/modoboa</pre>

**Comment by spinza** [comment]
Will try and give feedback.  Later today or tomorrow.
