### ISSUE TITLE
How can I mark false-negative spams?

### ISSUE THREAD

**Issue by m4dz** [modoboa/modoboa-amavis#32]
Hi there!

I'm using modoboa for a week (nice job :+1: !) and I'm trying to get amavis/spamassassin couple to work. I've installed modoboa and its extensions with the modoboa-installer on a PGSQL DB, without any problem (except that the spamassasin DB was empty, due to the lack of the sql file in the filesystem, not sure why… I've fixed it manually).

Now my problem is that I have a lot of spams, and they pass the spamassassin filter, so I want to mark them manually to let spamassassin learn about. Unfortunately, I can't see any _clean_ message in the quarantine. I can see, say,  _Banned_ messages, and mark them as spam successfully, but how can I get the _clean_ messages to mark them too?

Or is there anything that I misunderstand/misuse in the false-negative spam tagging process?

Thanks!

**Comment by tonioo** [comment]
Hi,
there are actually 2 ways to answer your need:
1. Add ```$clean_quarantine_method = 'sql:';``` to amavis configuration to put a copy of all clean messages into the quarantine. You'll then be able to use the learning feature provided by Modoboa
2. Confgure dovecot antispam plugin (http://wiki2.dovecot.org/Plugins/Antispam) to learn from your Junk folder.
I think option 2. could be automatically setup by the installer... I'll take a look into it asap.

**Comment by m4dz** [comment]
Great! I think too that option 2 should be the best way. I can confirm that `dovecot-antispam` isn't installed on my instance.

I'll try to configure it by myself, can you just explain to me how to do it properly (using mailtrain and the `sa-learn-pipe` script given as exemple, I suppose)?

Thanks!

**Comment by tonioo** [comment]
Yes, use that script (which is just a wrapper to sa-learn). The wiki explains the setup pretty well but don't hesitate to more help on IRC or the on the mailing list.

**Comment by m4dz** [comment]
Yep, just done it, it works like a charm! Let's see if the bayes filter training is efficient, now :wink:. Thanks for your time and your very good job!

**Comment by tonioo** [comment]
@m4dz Thank you ;)
Can I close the issue ?

**Comment by m4dz** [comment]
Yep, of course :)

**Comment by tonioo** [comment]
@m4dz BTW, you're using modoboa at Cozy ? Or just for you own need ? :)

**Comment by m4dz** [comment]
Ahah, just for my own needs at this time, but since Cozy do not embed a complete mail server, Modoboa is one of the solution we tend to recommend when we're asked for mail provider solution. But maybe one day, I hope we'll migrate our internal mails to Modoboa :wink:.

**Comment by tonioo** [comment]
Good to know ;-)

**Comment by cremesk** [comment]
@m4dz @tonioo
hi, a question.. can i copy & paste the dovecot config snippet and the sieve script's from https://doc.dovecot.org/configuration_manual/howto/antispam_with_sieve/ or i need to modify this?
