### ISSUE TITLE
Creating per-user policy from command line

### ISSUE THREAD

**Issue by zoc** [modoboa/modoboa-amavis#33]
Hi,

First of all, many thanks for your work on modoboa. This is really THE tool I always wanted to have to administer my mail server. Currently migrating from MacOSX Server to a Linux based solution using postfix+amavis+dovecot and modoboa, I'm in the process of configuring everything. However I would like to use the dovecot-antispam module to simplify reporting Spams/False positives for my users.

I have activated per-user training, and if I understand correctly, user policies are created only after first reporting spam/ham from the web interface. It means that dovecot-antispam per user cannot work until the user has reported at least one time from the web panel. Maybe I could leave with that, or find another way.

Do you see any solution to create users policies from a script ? I was thinking about adding a command to manage.py, but I must admit that I'm totally noob at writing python, and even more at using Django ;)

BTW I could try to implement something, but at least I would like to have some opinion about the feasibility.

Thank you.

**Comment by tonioo** [comment]
Hi,
you're absolutely right: per-user "users" records are created the first time a mail is reported from the interface...
I see two options to quickly solve this issue:
* Use a global database (amavis) to learn from all users
* Manually create an entry for every user as you proposed but it requires a bit of python knowledge

Another one, maybe more interesting, would be to create "users" record for every mailbox, by default. I think this is the best option but it requires code and a new release.

**Comment by zoc** [comment]
Thank you for the answer.

Finally I chose not to go this way and to rely on the user reporting at least one time using the web interface. 

My dovecot-antispam script, written in perl (I'm a little bit more comfortable writing perl) extracts sa_username from the dovecot username using a mysql stored procedure. This stored procedure tries to find the user policy from the user's full email address, then from the @domain part only, and fallbacks to returning "amavis" in case no sa_username is associated to the user or its parent domain.

This allows to train the bayesian database with the correct username in all cases, and this means that by default the global database will be trained, which is fine for me.
