### ISSUE TITLE
Per-user amavis policies not created

### ISSUE THREAD

**Issue by zoc** [modoboa/modoboa-amavis#34]
Hi,

I enabled Per-Domain and Per-user training and was expecting that the user being added to amavis.users, and a policy created in amavis.policy table the first time the user marks a message as spam or ham from the web interface.

What I see in practice:

1. The username appears in spamassassin.bayes_vars, confirming that sa-learn was called with the correct username.
2. In amavis.users, no entry is added. @domain entries are present, which confirms that this is not a permission issue.
3. In amavis.policy, no new entry is added. Only per-domain policies (without sa_username) are present, which confirms that this is not a permission issue.

It means that amavis will never use the user database but always the default one. Is this a known bug or did I missed something in the configuration ?

I'm using modoboa-amavis version 1.0.8 (was installed with pip a few days ago). I activated DEBUG mode but cannot see anything related to this issue in the Javascript console of the browser.

**Comment by zoc** [comment]
Ok, in fact it works... I was expecting that a simple user could activate his own database by reporting from his account. In fact, user database activation must be done by the domain administrator by first reporting a message.

Maybe this information should be added somewhere in the readme, because it could avoid confusions and disappointments ;)

**Comment by tonioo** [comment]
@zoc That's sound strange... Can you tell me how you activated manual learning ? (maybe a screenshot of your settings ?)

**Comment by zoc** [comment]
Sure, see attached screenshot.

![modoboa_settings](https://cloud.githubusercontent.com/assets/116463/15828783/fcbb1a0e-2c10-11e6-9296-7e9232da91e0.png)

**Comment by tonioo** [comment]
@zoc Could you try the fix I pushed please ?

**Comment by zoc** [comment]
I confirm that the issue does not occur anymore with your fix.

Thank you.
