### ISSUE TITLE
Documentation readthedocs

### ISSUE THREAD

**Issue by JeroenvO** [modoboa/modoboa-amavis#37]
The documentation in the git readme is different than http://modoboa-amavis.readthedocs.io/en/latest 
The documentation on readthedocs is insufficient.

**Comment by tonioo** [comment]
@JeroenvO What do you mean by insufficient? Should I add the readme content to the documentation?

**Comment by JeroenvO** [comment]
Yeah, that would be nice. Although the way to add a plugin to modoboa is obvious, it is not in the readthedocs documentation at this moment.
