### ISSUE TITLE
trivial question

### ISSUE THREAD

**Issue by JayBeRayBearGun** [modoboa/modoboa-amavis#40]
This must be truly trivial but I just want to check:

In the webinterface amavis settings, the notifications sender needs to be an exsisting local email address right? like admin@mydomain.com or amavisadmin@mydomain.com or notifications@mydomain.com

(definitely not notification@modoboa.org right?)

**Comment by tonioo** [comment]
Yes but people are not supposed to reply to notifications so you can even set a non-existing address. Just make sure it uses one of your domains (something like no-reply@mydomain.com).
I'll change the default value soon.
