### ISSUE TITLE
Spamfilter improvements

### ISSUE THREAD

**Issue by dragon2611** [modoboa/modoboa-amavis#41]
These are things I'd like to see with the spamfilter if possible in future releases.

1) Notification don't appear to work at the moment, means manually logging in and checking the quarantine, ideally an email sent at a certain time showing an quarantine summery

2) Feedback loop, there doesn't seem to be any obvious way to tell the spam filter it missed something, I don't want all clean emails in the quarantine and I've been led to believe the plugin to support learning from the junk folder in IMAP isn't suitable for production use.

3) Trusted IP's, So if using an external spam filtering service you can turn it off for any email that came through the service, but keep it on for anything else (Might not be possible to firewall SMTP if the modboa server hosts other domains)

**Comment by tonioo** [comment]
About 1., are you talking about a notification sent to administrators and giving them a summary of the quarantine content ?

About 2., I personally use the spam plugin of dovecot to learn from my Junk folder and it seems to work well but I don't have a lot of traffic. Why do you say it is not ready for production ?

About 3., I guess you're talking about amavis builtin white/black lists ?

**Comment by dragon2611** [comment]
1) Self service mode is on so in this case I'd expect the users to get them, I'd also expect the time they are sent to be configurable.

2) This is was the response to me from the service provider (The server in question is managed by them)

3) Indeed but I don't believe there is a frontend for this at the moment, it's possible I just missed it.

**Comment by tonioo** [comment]
So, I think 1. corresponds to #3 and 3. corresponds to #2.

About 3., I don't have any other idea to achieve the learning yet...

**Comment by dragon2611** [comment]
Maybe a Spam@domain mailbox, that said most people would forward to that so headers are unlikely to be preseved

**Comment by tonioo** [comment]
Looks a bit complicated for regular users... Maybe a button added to the webmail would be a better answer?

**Comment by dragon2611** [comment]
Fine if people are actually using the webmail, but if they're using a 3rd party webmail or IMAP that won't really work.

**Comment by tonioo** [comment]
Indeed. I suggest you give a try at the spam plugin for dovecot, it's pretty simple to setup and you'll make your own opinion. do you have a lot of users?

**Comment by dragon2611** [comment]
I'll ask the host (I don't have SSH access to that box to do it myself)

**Comment by pavinjosdev** [comment]
Hi @tonioo  Self service mode is not working as expected. Can confirm the settings in admin panel are being applied correctly since there are no errors in the console output with debug turned on. The actions aren't performed probably because the background job fails. Nothing of note in mail/uwsgi logs. Any thoughts on troubleshooting this? :)

**Comment by tonioo** [comment]
@pavinjosdev I've made some fixes about self service last week. Have you tested them? (last modoboa-amavis release)

**Comment by pavinjosdev** [comment]
Yes, applied [fix 43](https://github.com/modoboa/modoboa-amavis/issues/43) and still no emails sent.

**Comment by tonioo** [comment]
Can you describe the modifications you've done to your amavis config? Are you running 2.8 at least?

**Comment by pavinjosdev** [comment]
No mods to amavis other than a few lower SA thresholds & whitelist in 50-user; syntax & config files are correct. Version: amavisd-new-2.10.1 (20141025)

**Comment by tonioo** [comment]
Ok, so it means notifications are disabled. Look at ``$warnbannedrecip`` or ``$warnviruscecip`` flags as examples of notification.

**Comment by pavinjosdev** [comment]
Ty! That fixes it :)

**Comment by tonioo** [comment]
@dragon2611 any news?

**Comment by dragon2611** [comment]
Spam seems to be going to the spam folder and thus manageable via my IMAP client and I don't really get much else so Haven't seen notifications other than when we used a testing service.

I don't login to quarantine nearly as much these days

Slowly but surely training the spamfilter to my preferences.

**Comment by tonioo** [comment]
Ok, so I'll close this issue since others already exist to cover your questions.
