### ISSUE TITLE
Manual learning options missing/not available

### ISSUE THREAD

**Issue by pavinjosdev** [modoboa/modoboa-amavis#52]
# Impacted versions

* Modoboa: 1.7.2; Modoboa Amavis: 1.1.1
* Webserver: Nginx/Uwsgi

# Current behavior

Modoboa > Parameters > Amavis is missing per-domain and per-user manual learning options.

# Video/Screenshot link

Attached,
![1](https://cloud.githubusercontent.com/assets/11430516/24176117/6e3ffcd2-0e9a-11e7-9763-a8199ae744d4.PNG)

**Comment by tkald** [comment]
Under the quarantine I still don't have relevant buttons ("not spam") to manually train spammassassin.
I do have remote spammassassin and remote mysql quarantine database

![image](https://cloud.githubusercontent.com/assets/8062491/24524236/839a8db2-159e-11e7-80cd-807ff639e373.png)

And quarantine buttons
![image](https://cloud.githubusercontent.com/assets/8062491/24524336/d32e764a-159e-11e7-9a0b-97ef78fdd1fa.png)

Modoboa: 1.7.2; Modoboa Amavis: 1.1.1

**Comment by tonioo** [comment]
@tkald Could you try the fix I just pushed please?

**Comment by tkald** [comment]
@tonioo Yes, now I have missing button:

![image](https://cloud.githubusercontent.com/assets/8062491/24632280/39302512-18cc-11e7-9c12-ce7e59d0b2fc.png)

My setup is however bit unconventional - I use only amavis quarantine part (no domains/identities in modoboa database). So per-domain manual learning does not work.

**Comment by tonioo** [comment]
@tkald Indeed, I suggest you create domains if you want to use this feature.

**Comment by tkald** [comment]
I did create domain to modoba, but got error **[object Object]** if I chose recipient global database and no reaction if I chose "domain's database".

**Comment by pavinjosdev** [comment]
@tkald Please provide Debug response. (Enable Debug in settings.py)

**Comment by mundschenk-at** [comment]
@pavinjosdev @tonioo @tkald Probably the same issue here. Debug response indicates a path or permissions problem:
```
"message": "/bin/sh: spamc: not found\n"
```

However, `spamc` can be found in `/usr/local/bin/spamc`. This is with `Is Spamassassin local?` set to `Yes`.
