### ISSUE TITLE
Manual learning not working

### ISSUE THREAD

**Issue by mundschenk-at** [modoboa/modoboa-amavis#54]
Problem : Marking messages as spam/ham fails (continued from #52). 

Apparently, there are two problems with local SpamAssassin installations
1. The check for `sa_is_local` [uses comparison with the string "yes" but contains a boolean](https://github.com/modoboa/modoboa-amavis/blob/master/modoboa_amavis/lib.py#L106).
2. The `exec_cmd` call for the `_learn_cmd` fails due to some path/permissions issue.

**Comment by mundschenk-at** [comment]
I did get the commands to run by adding `/usr/local/bin/` to the command names.

**Comment by tonioo** [comment]
The path issue can be fixed at system level.

**Comment by mundschenk-at** [comment]
Thank you! 2. seems to have been an misconfiguriation on the uWSGI side (apparently you need to explicitely set the PATH variable),
