### ISSUE TITLE
Add hover descriptions for the filter types on Quarantine

### ISSUE THREAD

**Issue by stalks** [modoboa/modoboa-amavis#57]
I didn't understand what the filters at the top right of the Quarantine page.

C, S, V, H, M, B

I looked at the HTML title attribute to find out what they meant

**C**lean
**S**pam
**V**irus
Bad **H**eader
Bad **M**ime
**B**anned

Could add delayed hover tooltips to show what they mean for users.

**Comment by stalks** [comment]
Actually, would be good to add this to the left hand side column of the same type in the results.

I can see another type of "Y", which according to tests.py is "bypass_virus_checks"? Can there also be a filter for this? I don't understand what this one is for, and I have lots of them.

**Comment by tonioo** [comment]
According to Amavis documentation:
```
content     char(1),                   -- content type: V/B/U/S/Y/M/H/O/T/C
   -- virus/banned/unchecked/spam(kill)/spammy(tag2)/
   -- /bad-mime/bad-header/oversized/mta-err/clean
   -- is NULL on partially processed mail
   -- (prior to 2.7.0 the CC_SPAMMY was logged as 's', now 'Y' is used;
```
Looks like new values have been added since I implemented this feature...
