### ISSUE TITLE
Error opening webmail

### ISSUE THREAD

**Issue by danielsatanik** [modoboa/modoboa-amavis#63]
Opening webmail-tab displays a red error: "Sorry. An internal error occured."

<img width="1675" alt="screen shot 2017-07-28 at 21 56 21" src="https://user-images.githubusercontent.com/2507586/28734115-9d53150e-73df-11e7-9b16-e204371691b6.png">

Is there a way to provide more infos on what went wrong?

**Comment by tonioo** [comment]
What versions (modoboa and webmail) do you use?

**Comment by danielsatanik** [comment]
I'm using 1.8.2 modoboa and webmail is 1.2.0 now. I removed amavis (because I actually don't need it) and updated all the extensions. This is working now, so you can close it.
