### ISSUE TITLE
Database query speed for scalable mailservers

### ISSUE THREAD

**Issue by sNuuFix** [modoboa/modoboa-amavis#64]
Hello,

we are optimizing the speed of Modoboa's Quarantine tab for a server with 2000+ messages in a single workday and when we reach a few thousands of messages, the database query starts to time out the ajax requests for email_page. By studying the query log we found out multiple subqueries generated by Django's ORM and stumbled upon one filter that causes most of the slowness [by this line](https://github.com/modoboa/modoboa-amavis/blob/master/modoboa_amavis/sql_connector.py#L122) so we commented the filter out. It doesn't seem to affect much from interface's functionality but it does improve speed. The question is what it does and is it important? Also what else could be done to improve the speed of queries for large amount of messages in database?

**Comment by tonioo** [comment]
@sNuuFix  This line actually filters the queryset to include quarantined messages only, which is what we want. Can you tell me how you installed modoboa and what database engine you are using?
