### ISSUE TITLE
Problems with the configuration

### ISSUE THREAD

**Issue by Renatov** [modoboa/modoboa-amavis#92]
Hi in the modoboa_amavis module, there is a problem when you want to save the configuration data, your configuration, the browser gives this response and nothing is recorded,

An invalid form control with name = 'modoboa_radicale-server_location' is not focusable.

**Comment by tonioo** [comment]
Fixed by https://github.com/modoboa/modoboa/pull/1378.

**Comment by Renatov** [comment]
Hi, thank you very much
